markdown: kramdown

livereload: true

# URL of the Site
url: 
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Dragan Dimitrijevic
role: Freelancer
# Description of the Site
description: Online Portfolio
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Freelancer, Software Development, AWS Cloud, Nodejs
# URL for the Image of custom Favicon
favicon-url: 
# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://images.pexels.com/photos/220444/pexels-photo-220444.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: dragan@visidra.com
company: Visidra
facebook_username: dragan.dimitrijevic.7737
twitter_username: 
instagram_username: 
linkedin_username: ddragan
github_username:  dragandim
youtube_channel_id: 
reddit_username: 
behance_username: 
dribbble_username: 
spotify_username: 1140898604

# Google Analytics
google-analytics: G-5KQJ5V2HJ8

# Disqus
disqus-shortname: /

# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/dragandim

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
# permalink: "post/:title"
permalink: pretty

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
