# config pdf
destination: _site/
url: "http://127.0.0.1:4010"
baseurl: "/mydoc-pdf"
port: 4010
output: pdf
product: mydoc
print_title: Dragan Dimitrijevic
print_document: Curriculum Vitae
print_ocupation: Software Engineer
print_subtitle: version 3.4
output: pdf
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page_print"
      comments: true
      search: true

pdf_sidebar: mydoc_sidebar
